### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by basicde** [Ricky5panish/PE-Runtime-Crypter#1]
I can't get this to build

**Comment by Ricky5panish** [comment]
I used CLion IDE to create this projects. If you are using VS make sure to select x64 platform and use the multibyte character set in your settings. If you still get errors you may have to swich to MinGW and use the g++ compiler. It might be easier to switch to CLion IDE.
Here are my settings. 
![settings](https://user-images.githubusercontent.com/79810730/210341423-16c33e49-d5ad-4d18-bf2a-2c09ad7bada2.PNG)

**Comment by smorodinka13** [comment]
Hi. Please tell me, I ran into a problem in 2 point. It seems to have knocked down the stub.cpp  file in the exe. And how to insert a raw data into a crypter.cpp? Do I need to convert the exe somehow?
